/* autogenerated by running `gulp plugins` (see gulpfile.js) */
"use strict";
exports["fork-count"] = require("../plugins/fork-count");
exports["gh-pages-link"] = require("../plugins/gh-pages-link");
exports["pull-request-links"] = require("../plugins/pull-request-links");
exports["repo-counts"] = require("../plugins/repo-counts");
exports["repo-filter-info"] = require("../plugins/repo-filter-info");
exports.settings = require("../plugins/settings");
exports["twitter-link"] = require("../plugins/twitter-link");
exports.pluginNames = ["fork-count","gh-pages-link","pull-request-links","repo-counts","repo-filter-info","settings","twitter-link"];
